<?php

namespace Tests\Feature\Services;

use App\Models\User;
use App\Models\Client;
use App\Models\ClientSite;
use App\Models\Contract;
use App\Models\Attendance;
use App\Models\DailyAssignment;
use App\Models\Shift;
use App\Services\BillingService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Carbon\Carbon;

class BillingServiceTest extends TestCase
{
    use RefreshDatabase;

    protected $billingService;

    protected function setUp(): void
    {
        parent::setUp();
        $this->billingService = new BillingService();
        $this->seed(\Database\Seeders\RbacSeeder::class);
    }

    public function test_generate_invoice_per_day_logic()
    {
        // 1. Setup Data
        $client = Client::factory()->create();
        $site = ClientSite::factory()->create(['client_id' => $client->id]);
        $contract = Contract::create([
            'client_id' => $client->id,
            'contract_number' => 'CNT-TEST-001',
            'contract_type' => 'permanent',
            'start_date' => now()->startOfMonth(),
            'billing_type' => 'per_day', // Critical
            'rate_per_day' => 1000,
            'status' => 'active',
        ]);
        $contract->sites()->attach($site->id);

        $user = User::factory()->create(['role' => 'employee']);

        // 2. Create Attendance
        $date = '2026-02-01';
        
        // Create Assignment first (BillingService links them)
        $assignment = DailyAssignment::create([
             'user_id' => $user->id,
             'site_id' => $site->id,
             'contract_id' => $contract->id,
             'assigned_date' => $date,
             'status' => 'completed',
             'assigned_by' => $user->id, // Add this
        ]);

        Attendance::create([
            'user_id' => $user->id,
            'site_id' => $site->id,
            'date' => $date,
            'clock_in' => '09:00:00',
            'clock_out' => '18:00:00',
            'duration_minutes' => 540, // 9 hours
            'status' => 'present',
        ]);

        // Verify pivot
        $this->assertEquals(1, $contract->sites()->count());
        $this->assertEquals($site->id, $contract->sites()->first()->id);

        // 3. Generate Invoice
        $invoice = $this->billingService->generateInvoice(
            $contract,
            $date,
            $date,
            now()->addDays(15),
            User::factory()->create()->id // Generated By
        );

        // 4. Assert
        $invoice->refresh(); // Refresh to get calculated totals
        $this->assertNotNull($invoice);
        $this->assertEquals(1, $invoice->lineItems->count());
        $this->assertEquals(1000, $invoice->gross_amount); // 1 day * 1000
        $this->assertEquals(1180, $invoice->net_amount); // 1000 + 18% Tax
    }
}
